export const fyloData = [
    {
        id: 1,
        details: "Fylo has improved our team productivity by an order of magnitude. Since making the switch our team has become a well-oiled collaboration machine.",
        name: "Satish Patel",
        title: "Founder & CEO, Huddle",
    },
    {
        id: 2,
        details: "Fylo has improved our team productivity by an order of magnitude. Since making the switch our team has become a well-oiled collaboration machine.",
        name: "Bruce McKenzie",
        title: "Founder & CEO, Huddle",
    },
    {
        id: 3,
        details: "Fylo has improved our team productivity by an order of magnitude. Since making the switch our team has become a well-oiled collaboration machine.",
        name: "Iva Boyd",
        title: "Founder & CEO, Huddle",
    },

]